# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import user_data_pb2 as user__data__pb2


class GetUserDataStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUser = channel.unary_unary(
        '/GetUserData/GetUser',
        request_serializer=user__data__pb2.UserDataRequest.SerializeToString,
        response_deserializer=user__data__pb2.UserDataResponse.FromString,
        )


class GetUserDataServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetUserDataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=user__data__pb2.UserDataRequest.FromString,
          response_serializer=user__data__pb2.UserDataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GetUserData', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
