# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user_data.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fuser_data.proto\"\x1d\n\x0fUserDataRequest\x12\n\n\x02id\x18\x01 \x01(\x05\";\n\x10UserDataResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2?\n\x0bGetUserData\x12\x30\n\x07GetUser\x12\x10.UserDataRequest\x1a\x11.UserDataResponse\"\x00\x62\x06proto3')
)




_USERDATAREQUEST = _descriptor.Descriptor(
  name='UserDataRequest',
  full_name='UserDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserDataRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=48,
)


_USERDATARESPONSE = _descriptor.Descriptor(
  name='UserDataResponse',
  full_name='UserDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserDataResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='UserDataResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='UserDataResponse.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['UserDataRequest'] = _USERDATAREQUEST
DESCRIPTOR.message_types_by_name['UserDataResponse'] = _USERDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserDataRequest = _reflection.GeneratedProtocolMessageType('UserDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERDATAREQUEST,
  __module__ = 'user_data_pb2'
  # @@protoc_insertion_point(class_scope:UserDataRequest)
  ))
_sym_db.RegisterMessage(UserDataRequest)

UserDataResponse = _reflection.GeneratedProtocolMessageType('UserDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _USERDATARESPONSE,
  __module__ = 'user_data_pb2'
  # @@protoc_insertion_point(class_scope:UserDataResponse)
  ))
_sym_db.RegisterMessage(UserDataResponse)



_GETUSERDATA = _descriptor.ServiceDescriptor(
  name='GetUserData',
  full_name='GetUserData',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=111,
  serialized_end=174,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUser',
    full_name='GetUserData.GetUser',
    index=0,
    containing_service=None,
    input_type=_USERDATAREQUEST,
    output_type=_USERDATARESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETUSERDATA)

DESCRIPTOR.services_by_name['GetUserData'] = _GETUSERDATA

# @@protoc_insertion_point(module_scope)
